"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var generic_1 = require("./generic");
exports.isClientSide = generic_1.isClientSide;
var getLocale_1 = require("./getLocale");
exports.getInitialLocale = getLocale_1.getInitialLocale;
exports.getPrismicLocale = getLocale_1.getPrismicLocale;
var urlValidation_1 = require("./urlValidation");
exports.getRemainingLang = urlValidation_1.getRemainingLang;
exports.urlHasLocale = urlValidation_1.urlHasLocale;
