"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var config_1 = require("./config");
exports.defaultLocale = config_1.defaultLocale;
exports.locales = config_1.locales;
exports.prismicCultures = config_1.prismicCultures;
var generic_1 = require("./generic");
exports.isClientSide = generic_1.isClientSide;
exports.hasNavigator = generic_1.hasNavigator;
exports.localePathRegex = generic_1.localePathRegex;
var getLocale_1 = require("./getLocale");
exports.getInitialLocale = getLocale_1.getInitialLocale;
exports.getPrismicLocale = getLocale_1.getPrismicLocale;
var urlValidation_1 = require("./urlValidation");
exports.getLangFromUrl = urlValidation_1.getLangFromUrl;
exports.getRemainingLang = urlValidation_1.getRemainingLang;
exports.urlHasLocale = urlValidation_1.urlHasLocale;
exports.dummyLog = function (param) { return console.log('This is a param -->', param); };
